repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.80.0  # Check for latest: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs
        args: ["--args=--sort-by-required"]  # optional: format docs