name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::509403202865:role/GitHubActionsOIDCRole
          aws-region: ap-southeast-1  # or your region
          role-session-name: GitHubActionsSession
          audience: sts.amazonaws.com  # Added audience for OIDC authentication

      - name: Deploy Application
        run: |
          # Now that the AWS credentials are configured, any AWS CLI command
          # or AWS SDK-based deployment tool can be used without additional credentials
          aws s3 ls
