name: Terraform Plan (PR)

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Post Plan as Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            #### Terraform Plan 📐
            ```
            ${{ steps.plan.outputs.stdout }}
            ```